### ISSUE TITLE
EVOHD + IP150 via IP issues

### ISSUE THREAD

**Issue by acabutto** [ParadoxAlarmInterface/pai#124]
## Alarm system
- EVOHD
- IP150 via IP (unsure about firmware version, should be 4.10 according to logs)

## Environment
- MacOS Sierra 10.12.6
- Python 3.7.6

## Git branch
Tried with both master and dev

## Describe the bug
I have to admit that I'm a newbie here, I spent just a few hours playing with the software and config files, reading documentation, going though previous issues and collecting information about the environment. I hope that is something new and my contribution can be useful to improve this great project!

Going straight to the point:
I was able to establish a connection to the interface and panel but as soon as 'Updating Definitions from Panel' is logged the software crashes complaining about a missing key in mem_map in load_definitions method:

Traceback (most recent call last):
  File ".../pai/paradox/paradox.py", line 169, in connect_async
    definitions = await self.panel.load_definitions()
  File ".../pai/paradox/hardware/panel.py", line 141, in load_definitions
    definitions = self.mem_map['definitions']
KeyError: 'definitions'
Traceback (most recent call last):
  File ".../pai/paradox/paradox.py", line 169, in connect_async
    definitions = await self.panel.load_definitions()
  File ".../pai/paradox/hardware/panel.py", line 141, in load_definitions
    definitions = self.mem_map['definitions']
KeyError: 'definitions'

I noticed that the problem's root is in paradox/hardware/evo/models/evohd.py where mem_map is firstly defined for my EVOHD. Here there is no trace of "definitions" key while for all the others EVOs is there.

So I tried to copy & paste the "definitions" section from evo192.py and the issue  *apparently* went away, because now the procedure is able to go further:

[...]
2019-12-28 17:29:31,882 - INFO     - MainThread - PAI.paradox.hardware.panel - Updating Definitions from Panel
2019-12-28 17:29:31,907 - WARNING  - MainThread - PAI.paradox.paradox - Missing element ID in system/?, m/m: 37/6, message: Trouble restore: Clock loss restore
2019-12-28 17:29:32,456 - INFO     - MainThread - PAI.paradox.paradox - Loading labels
2019-12-28 17:29:32,456 - INFO     - MainThread - PAI.paradox.hardware.panel - Updating Labels from Panel
2019-12-28 17:29:33,163 - INFO     - MainThread - PAI.paradox.hardware.panel - Zone: XXX, XXX, XXX
[...]

Zones are reported correctly, but right after Doors reporting issues start again:

[...]
2019-12-28 17:32:34,371 - INFO     - MainThread - PAI.paradox.hardware.panel - Door: Door 01, Door 02, ..., Door 32
2019-12-28 17:32:34,533 - INFO     - MainThread - PAI.paradox.paradox - Connection OK
**2019-12-28 17:32:34,588 - ERROR    - MainThread - PAI.paradox.paradox - Got ERROR Message: Invalid record type
2019-12-28 17:32:40,520 - ERROR    - MainThread - PAI.paradox.paradox - Got ERROR Message: Invalid record type**
[...]

Maybe those errors are caused by my naive fix to evohd.py but my protocol knowledge is not deep enough to say more.

Full logs attached as encrypted file.

Thanks for any help you can provide!

## To Reproduce
1. Start script ./run.sh
2. Add a "definitions" section to 'paradox/hardware/evo/models/evohd.py' file
3. See error

## Logs
Please se attached.
[paradox.txt](https://github.com/ParadoxAlarmInterface/pai/files/4007226/paradox.txt)

**Comment by yozik04** [comment]
Actually the fix is right. Will add it. At today’s state master=dev.

**Comment by yozik04** [comment]
@jpbarraca can you please send me decrypted logs.

**Comment by yozik04** [comment]
Added definitions in 6b7de26

**Comment by yozik04** [comment]
@acabutto Please pull latest dev. Try. Encrypt logs with debug and send to `yozik04`. That will be faster. I am developing EVO branch so it will be targeted to the right person.

**Comment by yozik04** [comment]
Fixed in 1.4.0

**Comment by acabutto** [comment]
@yozik04 thanks for finding the time to get back to me :)

I've been away few days for holidays, as soon as I can connect my notebook to my home wifi I'll test the new version and provide feedback!

**Comment by acabutto** [comment]
> @acabutto Please pull latest dev. Try. Enable debug. Collect logs, encrypt and send to `yozik04`. That will be faster. I am developing EVO branch so it will be targeted to the right person.

@yozik04 just tested latest dev version with no success (still getting 'Got ERROR Message: Invalid record type'). I have collected the full debug log but I cannot send it to you using keybase, it says 'Error: Cannot find a public key for 'yozik04' when I click on 'Encrypt'.

**Comment by yozik04** [comment]
Ahh. I did not uploaded that. Ok. Send to my mail. Nickname @gmail.com

**Comment by yozik04** [comment]
Did you read about EVO specifics in the wiki?

**Comment by acabutto** [comment]
> Ahh. I did not uploaded that. Ok. Send to my mail. Nickname @gmail.com

Email on the way!

**Comment by acabutto** [comment]
> Did you read about EVO specifics in the wiki?

Just had a look to the specifics and realized that I had to tweak STATUS_REQUESTS in the config file. By doing that now the system seams to work well!

Playing with MQTT interface now ;)

**Comment by yozik04** [comment]
😆 ok. Great then
